ALTER TABLE `users` ADD COLUMN `sexo` TINYINT NULL DEFAULT 1  AFTER `fb_data`;
ALTER TABLE `users` ADD COLUMN `temp` VARCHAR(16) NULL  AFTER `sexo`;
ALTER TABLE `users` ADD COLUMN `fecha_nacimiento` DATETIME NULL DEFAULT NULL  AFTER `temp` ;